<!DOCTYPE html>

<?php
/**
 * Category
 *
 * Displays all the blog posts from a single category
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

// 1/28/19 - Seems to be working.
// Passing the correct category to content.php

get_header(); ?>
<?php get_sidebar(); ?>
<div id="blog-menu">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <!-- contents of the loop -->

      <?php get_template_part( 'content', get_post_format() ); ?>

      <?php
      if ( has_post_thumbnail() ) {
          $featured_image = get_the_post_thumbnail();
      } ?>

    <?php endwhile; endif; ?>
		<nav id="nav-home">
				<a href="<?php echo esc_url( home_url( '/' ) ); ?>"><em>HOME</em></a>
		</nav>
</div>
<!-- end blog-menu -->
<?php get_footer(); ?>
