<?php
/**
 * Content
 *
 * Displays a sigle blog post
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

?>

<div class="blog-post">
<!-- BEGIN BLOG POST	 -->
  <a  class="featured-image" href="<?php the_permalink(); ?>">
  	<div class="image-wrapper">
	  <?php echo the_post_thumbnail(); ?>
	</div>
  </a>
  <div id="title-summary">
    <a href="<?php the_permalink(); ?>"><div class="title"><p><?php the_title(); ?></p></div></a>
    <div class="summary"><p><?php the_content(); ?></p></div>
  </div>
<!-- END BLOG POST -->
</div>
