<?php
/**
 * Footer
 *
 * Displays a page footer
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>

      <footer id="footer">
        <div class="footer-item">
			<span>+1 781.934.6752</span>
		</div>
        <div class="footer-item">
			<span><a href="https://travelsommelier.com" target="_blank">travelsommelier.com</a></span>
		</div>
        <div class="footer-item">
			<span>
				<a href="https://travelsommelier.com/about/contact-us/" target="_blank">CONTACT US</a>
			</span>
		</div>
        <div class="footer-item">
          <span>
			  <a href="https://www.facebook.com/travelsommelier/" target="_blank"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/social-icons/fb_icon.png" alt="facebook icon"></a>
			  <a href="https://www.instagram.com/travelsommelier1/" target="_blank"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/social-icons/in_icon.png" alt="instagram icon"></a>
			  <a href="https://www.linkedin.com/company/2245870/admin/" target="_blank"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/social-icons/ln.png" alt="linkedIn icon"></a>
			  <a href="https://twitter.com/travelsommelier" target="_blank"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/social-icons/tw_icon.png" alt="twitter icon"></a>
			</span>
        </div>
      </footer>
    </div> <!-- end grid wrap -->
</div><!-- end full page wrap -->
 <?php wp_footer(); ?>
</body>
</html>
