<!DOCTYPE html>

<?php
/**
 * Home
 *
 * Displays the default home page
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}


get_header(); ?>
<?php get_sidebar(); ?>
<div id="blog-menu">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <!-- contents of the loop -->

      <?php get_template_part( 'content', get_post_format() ); ?>

      <?php
      if ( has_post_thumbnail() ) {
          $featured_image = get_the_post_thumbnail();
      } ?>

    <?php endwhile; endif; ?>
</div>
<!-- end blog-menu -->
<?php get_footer(); ?>
