
<?php
/**
 * Single Content
 *
 * Displays the content of a single blog post
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>

  <article id="single-blog-post">

    <div class="single-post-title"><p><?php the_title(); ?></p></div>
    <div class="single-post-content"><p><?php the_content(); ?></p></div>

		<!-- Navigation code -->
		<?php
			 $current_category = get_the_category();
			 //$current_category[0]->term_id; used to access first array in nested array.
			 //may need to rework this if there are problems later!
			 $category_id = $current_category[0]->term_id;
 			$category_name = get_cat_name( $category_id );

 	    // Get the URL of this category
 	    $category_link = get_category_link( $category_id );
 			$category_desc = category_description( $category_id );
		?>

		<nav id="nav">
			<div class="nav-item"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a></div>
			<div class="dropdown nav-item">
  			<button class="dropdown-toggle" type="button" data-toggle="dropdown">Other categories
  				<span class="caret"></span></button>
				<ul class="dropdown-menu">
					<li class=""><a href="<?php echo esc_url( $category_link ); ?>">Category name: <?php echo $category_name; ?></a></li>
					<li class=""><a href="<?php echo esc_url( $category_link ); ?>">Category name: <?php echo $category_name; ?></a></li>
					<li class=""><a href="<?php echo esc_url( $category_link ); ?>">Category name: <?php echo $category_name; ?></a></li>
					<li class=""><a href="<?php echo esc_url( $category_link ); ?>">Category name: <?php echo $category_name; ?></a></li>
				</ul>
			</div>
			<div class="nav-item"><a href="<?php echo esc_url( $category_link ); ?>">Category name: <?php echo $category_name; ?></a></div>
			<div class="nav-item">
				<?php previous_post_link('&laquo; %link', '%title', true); ?>
			</div>
			<div class="nav-item">
			<?php next_post_link('%link &raquo;', '%title', true); ?>
		 	<?php /* next_post_link('%link', 'Next post in category', TRUE); */ ?>
			</div>

		</nav>
  </article>
