
<?php
/**
 * Single Content
 *
 * Displays the content of a single blog post
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>

  <article id="single-blog-post">


    <div class="single-post-content">
			<div class="single-post-title">
				<p><?php the_title(); ?></p>
			</div>

			<p>
				<?php the_content(); ?>
			</p>
		</div>

		<?php get_template_part( 'full-nav', get_post_format() ); ?>

  </article>
