
<?php
/**
 * Single Content
 *
 * Displays the content of a single blog post
 *
 * @link http://www.joehiggins.me
 *
 * @package      travel-essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>

  <article id="single-blog-post">
    <div class="single-post-title"><p><?php the_title(); ?></p></div>
    <div class="single-post-content"><p><?php the_content(); ?></p></div>

  </article>
