<!DOCTYPE html>

<?php
/**
 * Home
 *
 * Displays the default home page
 *
 * @package      Travel Essence
 * @license      license.txt
 * @copyright    2019 Joe Higgins
 * @since        0.0.1
 *
 * Please do not edit this file.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}


get_header(); ?>
<?php get_sidebar(); ?>
<div id="blog-menu">
  <h1>INDEX.php</h1>
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <!-- contents of the loop -->

      <?php get_template_part( 'content', get_post_format() ); ?>

      <?php
      if ( has_post_thumbnail() ) {
          $featured_image = get_the_post_thumbnail();
      } ?>

    <?php endwhile; endif; ?>
</div>
<!-- end blog-menu -->
<?php get_footer(); ?>
